-- Local development seed. Glossary terms are global content; production gets them via a migration
-- once the curated list is agreed (docs/PLAN.md open question: glossary source).

insert into public.glossary_term (slug, term, aliases, definition, match_rules, plain_phrasing) values
  ('sous-vide', 'sous vide', '{}',
   'Cooking food sealed in a bag in a water bath held at a precise, low temperature.',
   '{}', 'cook in a sealed bag in a temperature-controlled water bath'),
  ('deglaze', 'deglaze', '{}',
   'Adding liquid to a hot pan to lift the browned bits stuck to the bottom into a sauce.',
   '{}', 'pour in liquid and scrape up the browned bits'),
  ('fold', 'fold', '{}',
   'Gently combining a light mixture into a heavier one with a cutting and turning motion, keeping the air in.',
   '{"excludeNear": ["pastry", "dough", "half", "over", "napkin", "edges", "sides"]}',
   'gently mix in without stirring hard'),
  ('reduce', 'reduce', '{}',
   'Simmering a liquid uncovered so water evaporates and it thickens and intensifies in flavour.',
   '{"excludeNear": ["heat", "temperature", "oven", "speed", "flame"]}',
   'simmer uncovered until thicker'),
  ('blanch', 'blanch', '{}',
   'Briefly boiling food, then plunging it into cold water to stop it cooking.',
   '{}', 'boil briefly, then cool in cold water'),
  ('julienne', 'julienne', '{}',
   'Cutting into long, thin matchstick strips.',
   '{}', 'cut into thin matchsticks'),
  ('chiffonade', 'chiffonade', '{}',
   'Stacking and rolling leaves, then slicing across into fine ribbons.',
   '{}', 'roll up the leaves and slice into thin ribbons'),
  ('temper', 'temper', '{"tempering"}',
   'Slowly raising the temperature of a delicate ingredient (like eggs) by adding hot liquid gradually so it doesn''t curdle.',
   '{"excludeNear": ["spices", "spice", "chocolate"]}',
   'add the hot liquid a little at a time while stirring'),
  ('cream', 'cream', '{}',
   'Beating butter and sugar together until pale and fluffy.',
   '{"requireNear": ["butter", "sugar", "margarine"]}',
   'beat until pale and fluffy'),
  ('rest', 'rest', '{"resting"}',
   'Leaving cooked meat or dough undisturbed so juices redistribute or gluten relaxes.',
   '{"requireNear": ["meat", "steak", "dough", "joint", "loaf", "lamb", "beef", "pork", "chicken", "turkey", "batter"]}',
   'leave it alone for a while');
